FROM node:24

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    curl \
    procps \
    sudo \
    corkscrew \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /home/node/.gemini /usr/local/share/npm-global && \
    chown -R node:node /home/node/.gemini /usr/local/share

WORKDIR /home/node

USER node

ENV TERM=xterm-256color
ENV NPM_CONFIG_PREFIX=/usr/local/share/npm-global
ENV PATH=$PATH:/usr/local/share/npm-global/bin

RUN npm i -g @google/gemini-cli

CMD ["gemini"]
